### PR TITLE
Fix typo on NFTs page

### PR DESCRIPTION
**Pull request by SynthwaveAndy**
Fixed a typo in the Primitives/NFTs page. 

The header was "**Decision Decisions**"
Assuming it was supposed to be "**Design Decisions**"

### CODE REVIEW

**Review by Rigidity — APPROVED** [review]

**Comment by Rigidity** [comment]
@SynthwaveAndy your commit is unsigned, which prevents it from being merged into this repo. Are you able to either sign the commit or create a new PR with a commit that is signed?

https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Review by BrandtH22 — APPROVED** [review]
lgtm

**Comment by BrandtH22** [comment]
@SynthwaveAndy your commit is unsigned, which prevents it from being merged into this repo. Are you able to either sign the commit or create a new PR with a commit that is signed?

https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by BrandtH22** [comment]
This will be included in an upcoming pr

**Pull request closed without merging**
